site_name: 'DWE & ARCAVIO - Businessplan'
site_description: 'Generalübernehmung für energetische Gebäudesanierung'
site_author: 'Sebastian Möhrer'
site_url: 'https://dwe-arcavio-businessplan.github.io'

# Repository
repo_name: 'dwe-arcavio/businessplan'
repo_url: 'https://github.com/dwe-arcavio/businessplan'

# Configuration
theme:
  name: material
  language: de
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy

# Plugins
plugins:
  - search:
      lang: de
  - glightbox

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

# Navigation
nav:
  - 'Startseite': 'index.md'
  - 'Geschäftsmodell': '01-geschaeftsmodell.md'
  - 'Gesellschafterstruktur': '02-gesellschafterstruktur.md'
  - 'Meilensteine': '03-meilensteine.md'
  - 'Finanzplanung': '04-finanzplanung.md'
  - 'Zielgruppen': '05-zielgruppen.md'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dwe-arcavio
    - icon: fontawesome/solid/globe
      link: https://www.dwe-arcavio.de
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # Hier Ihre Google Analytics ID einfügen

# Copyright
copyright: Copyright &copy; 2025 DWE & ARCAVIO - Sebastian Möhrer